### ISSUE TITLE
how we get to know that from which account(google account) we authorized

### ISSUE THREAD

**Issue by sachin81094** [googleads/googleads-dotnet-lib#108] opened 2017-08-18 10:31 UTC
Hello,
I am using asp.net web application to record conversions on google adwords account.I am using oauth2.0 flow to authorize the user's accounts (google account). I want to know fee things regarding this flow:
1) How I can get refresh token every-time I authorize the same google account
2) Is google authorization API returns any unique parameter or code for authorized account (google account), through which I can identify that this user previously authorized or not

If Point 1 is not possible: So is there any way or unique parameter to find that this account is already authorized for my app. So I can use the previous token that I get the first time for that account 

Thanks

**Comment by AnashOommen** [comment] 2017-08-24 23:50
Duplicate of #110

**Closed by AnashOommen** 2017-08-24 23:50 UTC
