### ISSUE TITLE
No proxy support under .NET Core 2.2

### ISSUE THREAD

**Issue by arnamq** [googleads/googleads-dotnet-lib#201] opened 2018-12-19 06:55 UTC
Hi,

My project uses .NET Core 2.2 under CentOS Lunux (docker) and it seems that a client library ignores env proxy settings (http_proxy & https_proxy). The OAuth authorization (ADUser) uses a proxy settings but ReportJob ignores it.

Kind regards,
Piotr

**Comment by arnamq** [comment] 2018-12-27 11:53
I've found couse ot the problem. AdManager library has reference to the System.ServiceModel.Http 4.4.2 and there was a bug with a proxy support in that version. If I force my app tu use System.ServiceModel.Http 4.5 everything works fine.

Could you please update the dependencies to use the newset version of System.ServiceModel.Http?

**Comment by christopherseeley** [comment] 2019-02-26 14:47
Duplicate of #133

**Closed by christopherseeley** 2019-02-26 14:47 UTC
Labels: duplicate
