### ISSUE TITLE
Logging showing up in User-Agent string

### ISSUE THREAD

**Issue by oaknguyen** [googleads/googleads-dotnet-lib#99] opened 2017-05-11 18:37 UTC
Hey there,

I'm currently having an issue as described [here](https://groups.google.com/forum/#!topic/adwords-api/-aag8pFYhpc). Essentially I'm getting an "invalid grant" response when I try to use the refresh token. I've talked to the api team and they told me that the question below might be better suited for this library team. 

So in my attempt to debug the issue, I started by using RefreshToken() on two token, one that I know works and the problematic token. Then capturing the requests shown below

problematic token
> POST /o/oauth2/token
> User-Agent: (AwApi-DotNet/18.29.0, Common-Dotnet/3.15.0, .NET CLR/4.0.30319.42000, Logging, OAuthApplicationFlow, gzip)
> Content-Type: application/x-www-form-urlencoded
> Host: accounts.google.com
> TimeStamp: Wed, 10 May 2017 11:44:28 GMT
> 
> client_id=*********.apps.googleusercontent.com&client_secret=******&refresh_token=******&grant_type=refresh_token

working token
> POST /o/oauth2/token
> User-Agent: (AwApi-DotNet/18.29.0, Common-Dotnet/3.15.0, .NET CLR/4.0.30319.42000, OAuthApplicationFlow, gzip)
> Content-Type: application/x-www-form-urlencoded
> Host: accounts.google.com
> TimeStamp: Wed, 10 May 2017 12:01:07 GMT
> 
> client_id=*********.apps.googleusercontent.com&client_secret=******&refresh_token=******&grant_type=refresh_token

The only difference i see here seems to be the "Logging" in the User-Agent string of the problematic token. I was just wondering 

1. What is that "Logging"?
2. Why is it present for the problematic case?
3. How can I remove if it's part of this problem?

Thank you for taking a look at this and please let me know if you need anymore details. 
-Oak

**Comment by AnashOommen** [comment] 2017-05-11 20:08
Hi Oak,

This behaviour is controlled by the IncludeUtilitiesInUserAgent flag: https://github.com/googleads/googleads-dotnet-lib/wiki/Understanding-App.config#general-library-behavior

You can make the issue go away (assuming that's the root cause) by just setting this flag to false. However, I want to make sure that's indeed the root cause of the issue. Could you pls drop me an email to adwordsapiadvisor+anash@google.com? Pls mention this bug number and add an attn:Anash to the email so it reaches me.

**Comment by AnashOommen** [comment] 2017-05-25 21:23
Closing this issue since the logging useragent param doesn't seem to have an influence here. Investigating separately on product support queue.

**Closed** 2017-05-25 21:22 UTC
