### ISSUE TITLE
Async Support for Services

### ISSUE THREAD

**Issue by omerkorenn** [googleads/googleads-dotnet-lib#102] opened 2017-05-29 17:27 UTC
Hi Guys,
After months of suffering in our company,
We decided to automate the process of creating all async overloads to the SDK.

We just upgrade the SDK and compile the source ourselves. (consume it internally)

You can use the code to upgrade the SDK with the tool that is published here:
https://github.com/omerkorenn/adwords-sdk-asyncer

Have Fun !

**Comment by AnashOommen** [comment] 2017-05-30 01:08
Copying the code here for brevity.

Step 1: Add this method to `AdsSoapClient.cs`.

```
protected async Task<object[]> InvokeAsync(string methodName, object[] parameters) {
  var action = new Func<AsyncCallback, object, IAsyncResult>((y, x) => { return 
    base.BeginInvoke(methodName, parameters, y, x); });
    while (true) {
      InitForCall(methodName, parameters);
      try {
        return await Task.Factory.FromAsync(action, base.EndInvoke, null);
      } catch (SoapException ex) {
      ErrorHandler errorHandler = CreateErrorHandler();
      Exception customException = GetCustomException(ex);
      if (errorHandler.ShouldRetry(customException)) {
        errorHandler.PrepareForRetry(customException);
      } else {
        throw customException;
      }
    } catch (Exception ex) {
      throw;
    } finally {
      CleanupAfterCall(methodName, parameters);
    }
  }
}
```

Step 2: Generate a method like this:

```
public async Task<AdGroupAdReturnValue> mutate(
 [System.Xml.Serialization.XmlElementAttribute("operations")] AdGroupAdOperation[] operations {
  Task<object[]> results = this.InvokeAsync("mutate", new object[] {
    operations
  });
  return ((AdGroupAdReturnValue)((await results)[0]));
}
```

Did I capture this correctly?

**Comment by omerkorenn** [comment] 2017-05-30 10:21
Yes indeed, that's right,
Maybe you can reference to an old issue about this topic.

**Comment by AnashOommen** [comment] 2017-09-05 15:18
Marking as duplicate of #2 .

**Closed by AnashOommen** 2017-09-05 15:18 UTC
