### ISSUE TITLE
Could it support on universal app?

### ISSUE THREAD

**Issue by Englbach** [googleads/googleads-dotnet-lib#53] opened 2015-08-21 11:34 UTC
I installed google.ads but it don't support.

**Comment by AnashOommen** [comment] 2015-08-31 18:30
Hi,
I haven't tried this yet, but I'll accept this as an item for further investigation.

**Comment by AnashOommen** [comment] 2015-08-31 18:40
Duplicate of issue #51

**Closed by AnashOommen** 2015-08-31 18:40 UTC
